use standard syntax for defining bin entrypoint
foresterre/cargo-msrv pull request #216
Opened 2021-12-16 08:55 UTC by danieleades

this PR makes a change to use the standard layout for defining a binary entrypoint. Namely that `src/main.rs` is implicitly treated as a binary target, without needing to be explicitly defined.

2021-12-20 11:05 UTC, foresterre commented
Hi @danieleades,

Thanks for the PR's; I will start with this PR, and throughout the week I aim to work my way through your other PR's as well (I'm really busy so it may take a bit longer than I would usually like). Thank you for your patience!

2021-12-20 11:08 UTC, foresterre requested changes
I really like the expliciteness of the `bin/<binary_name>.rs` binary targets. Since this project only has one target, the `[[bin]]` section is redundant.
As such, I will keep the `bin/cargo-msrv.rs` binary target in place, but feel free to remove the `[[bin]]` target section.

2021-12-20 11:24 UTC, danieleades commented
> I really like the expliciteness of the `bin/<binary_name>.rs` binary targets. Since this project only has one target, the `[[bin]]` section is redundant. As such, I will keep the `bin/cargo-msrv.rs` binary target in place, but feel free to remove the `[[bin]]` target section.

i was under the impression that you could only have an implicit `bin` section if the bin target was located at `src/main.rs`?

2021-12-20 11:25 UTC, foresterre commented
> > I really like the expliciteness of the `bin/<binary_name>.rs` binary targets. Since this project only has one target, the `[[bin]]` section is redundant. As such, I will keep the `bin/cargo-msrv.rs` binary target in place, but feel free to remove the `[[bin]]` target section.
> 
> i was under the impression that you could only have an implicit `bin` section if the bin target was located at `src/main.rs`?

I just tested it, at least with `cargo run`, it seems to work fine :)

2021-12-20 11:28 UTC, danieleades commented
> I just tested it, at least with `cargo run`, it seems to work fine :)

everyday's a school day!

another option would be to use a virtual manifest, and split them entirely into separate crates. Is that something you've considered?

2021-12-20 14:04 UTC, foresterre requested changes
I think you forgot to rename the file name back to cargo-msrv.rs (currently it's `src/bin/main.rs` instead of `src/bin/cargo-msrv.rs`)

2021-12-20 14:04 UTC, foresterre commented
Could you also please rebase and squash these commits in one commit?, thanks!

2021-12-20 14:07 UTC, danieleades commented
> Could you also please rebase and squash these commits in one commit?, thanks!

you can do that using `squash merge` through the UI (might make sense to make that the default)

2021-12-20 14:11 UTC, foresterre commented
> > Could you also please rebase and squash these commits in one commit?, thanks!
> 
> you can do that using `squash merge` through the UI (might make sense to make that the default)

Isn't that only the case when using the github UI to merge PR's? :)

I'm using [bors](https://bors.tech/) to merge PR's via a merge queue. Bors, doesn't, to the best of my knowledge, have such an option.

2021-12-20 14:13 UTC, danieleades commented
> I'm using [bors](https://bors.tech/) to merge PR's via a merge queue. Bors, doesn't, to the best of my knowledge, have such an option.

ah i see. i'll make sure i squash these for in future in that case

2021-12-20 14:20 UTC, foresterre requested changes
> I think you forgot to rename the file name back to cargo-msrv.rs (currently it's src/bin/main.rs instead of src/bin/cargo-msrv.rs)

😉

2021-12-21 10:18 UTC, foresterre commented
bors r+

2021-12-21 10:18 UTC, foresterre approved these changes

2021-12-21 10:30 UTC, merged