simplify cli for 'list' command
foresterre/cargo-msrv pull request #352
Opened 2022-04-27 05:11 UTC by danieleades

use `Clap`'s built-in `ArgEnum` trait, rather than implementing this manually

2022-04-27 23:00 UTC, foresterre requested changes

2022-04-27 23:00 UTC, foresterre commented on src/dependencies/formatter/ordered_by_msrv.rs
> +        variant: "ordered-by-msrv",
Same here :).

2022-05-21 00:20 UTC, foresterre commented
Hey @danieleades, I hope you're doing OK :). Would you mind if I took over the PR and completed it, or would you like to make the requested changes?

2022-05-21 05:46 UTC, danieleades commented
> Hey @danieleades, I hope you're doing OK :). Would you mind if I took over the PR and completed it, or would you like to make the requested changes?

i won't get a chance to look at this for a couple of weeks, i think. i don't mind either way

2022-10-13 18:36 UTC, closed without merging